<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
  <head>
    <title>Administration</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="blog.css">
    <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
  </head>
  
  <body>
    <p><a href=".">Accéder à l'accueil du site</a></p>
    
    <form action="admin.phtml" method="post">
      <p style="text-align: center">


        Auteur : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="auteur"/><br />
        
        Titre :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="titre"/><br />

        Catégorie : <input type="number" name="categorie"/><br /><br />
        
        Contenu :<br /><textarea rows="8" cols="60" name="contenu"></textarea><br /><br />

      <input type="submit" value="Ajouter" />

      </p>
    </form>

      <?php
        require_once ('includes/autoload.php');
        $posts = new Model_Post();


        if (isset($_GET['supprimer']))
        {
          $id = $posts->deletetPost( $_GET['supprimer'] );

        }




        if (  array_key_exists("auteur", $_POST) && array_key_exists("titre", $_POST) &&
              array_key_exists("categorie", $_POST) && array_key_exists("contenu", $_POST) )
        {

          $auteur     = $_POST["auteur"];
          $titre      = $_POST["titre"];
          $categorie  = $_POST["categorie"];
          $contenu    = $_POST["contenu"];

          $id = $posts->insertPost($auteur, $titre, $contenu, $categorie);
        }

      ?>



      <?php
        require_once ('includes/autoload.php');
        $posts = new Model_Post();
        $nompst = $posts->getLatestPosts(0);

        echo '<p style="text-align: center">' . count($nompst) . ' nouvelles actuellement en ligne';
        echo '<p style="text-align: center">' . ' Liste des nouvelles:';



      ?>
    
    <table>
      <tr class="ad_tr_liste">
        <td class="ad_td_auteur">Auteur</td>
        <td class="ad_td_titre">Titre</td>
        <td class="ad_td_cetegorie">Catég.</td>
        <td class="ad_td_date_ajout">Date d'ajout</td>
        <td class="ad_td_date_modif">Dernière modification</td>
        <td class="ad_td_action">Action</td>
      </tr>



      <?php
        for ($i=0; $i<count($nompst); $i++)
        {
          echo '<tr>';
          echo '<td class="ad_td_auteur">'      . $nompst[$i]['auteur']     . '</td>'; 
          echo '<td class="ad_td_titre">'       . $nompst[$i]['titre']      . '</td>';
          echo '<td class="ad_td_cetegorie">'   . $nompst[$i]['categorie']  . '</td>';
          echo '<td class="ad_td_date_ajout">'  . substr($nompst[$i]['dateAjout'],0,10)  . '</td>';
          echo '<td class="ad_td_date_modif">'  . substr($nompst[$i]['dateModif'],0,10)  . '</td>';
          echo '<td class="ad_td_action">'      .
               '<a href="admin.phtml">Modifier</a><br>
                <a href="?supprimer=', $nompst[$i]['id'], '">Supprimer</a>' .
               '</td>';
          echo '</tr>';
        }
      ?>

    </table>


  </body>
</html>

<!-- <a href="?supprimer=', $news->id(), '">Supprimer</a> -->