
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">

  <head>
    <title>TP Blog vassigh</title>
    <link rel="stylesheet" href="blog.css">
    <meta charset="utf-8">
    <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
    
  </head>
  
  <body>

     <h1 style="text-align: center">Les 5 dernières</h1>

      <?php
        $posts = new Model_Post();
        $nompst = $posts->getLatestPosts(5);

        for ($i=0; $i<2; $i++)
        {
          echo '<div>';
          echo '<p class="titre">' . 
                  'Auteur : '      .
                  '<span class="texte">'  . $nompst[$i]['auteur'] . '</span>' .
               '</p>'; 

          echo '<p class="titre"><a href = "contenu.php?id=' . $nompst[$i]['id'] . '">' .
                  'Titre : '      .
                  '<span class="texte">'  . $nompst[$i]['titre']  . '</span>' .
                '</a></p>';

          echo '<p class="contenu">' .
             substr( $nompst[$i]['contenu'], 0, 100 ) . '</p>';

          echo '<p class="titre">' .
                 'Catégorie : '          . 
                  '<span class="texte">'  . $nompst[$i]['categorie']  . '</span>' .
                '</p>';

          echo '<p class="titre">' .
                 'Date de création : '          . 
                  '<span class="texte">'  . $nompst[$i]['dateAjout']  . '</span>' .
                '</p>';

          echo '<p class="titre">' .
                 'Date dernière modification : '          . 
                  '<span class="texte">'  . $nompst[$i]['dateModif']  . '</span>' .
                '</p>';
          echo '</div>';
        }
      ?>

  </body>
</html>

