<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
  <head>
    <title>Administration</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="blog.css">
    <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
  </head>
  
  <body>
    <p><a href=".">Accéder à l'accueil du site</a></p>
    
    

      <?php
        require_once ('includes/autoload.php');
        $posts = new Model_Post();


        if (isset($_GET['supprimer']))
        {
          $id = $posts->deletetPost( $_GET['supprimer'] );

        }

        if (  array_key_exists("auteur", $_POST)    && !empty($_POST["auteur"])     &&
              array_key_exists("titre", $_POST)     && !empty($_POST["titre"])      &&
              array_key_exists("categorie", $_POST) && !empty($_POST["categorie"])  &&
              array_key_exists("contenu", $_POST)   && !empty($_POST["contenu"])  )
        {

            $auteur     = $_POST["auteur"];
            $titre      = $_POST["titre"];
            $categorie  = $_POST["categorie"];
            $contenu    = $_POST["contenu"];

          if (!isset($_GET['modifier']) )
          {




            $id = $posts->insertPost($auteur, $titre, $contenu, $categorie);
          }
          else
          {
           
            $id = $posts->updatePost($_GET['modifier'], $auteur, $titre, $contenu, $categorie);
          }

        }

        $nompst = $posts->getLatestPosts(0);


        if (  isset($_GET['modifier']) ) 
        { 
          $modif=0;
          while ( $nompst[$modif]['id'] != $_GET['modifier'] )
           {
             $modif++;
           } 
        }

      ?>

        <?php
            if (  isset($_GET['modifier']) ) 
            { 
              echo '<form action="admin.phtml?modifier=' . $_GET['modifier'] . '" method="post">';
            }
            else
            { 
              echo '<form action="admin.phtml" method="post">';
            }
        ?>


 <!--     <form action="admin.phtml" method="post">  -->
        <p style="text-align: center">

          Auteur : &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="auteur"
             value="<?php echo @$nompst[$modif]['auteur'];?>"/><br />
          
          Titre :  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" name="titre"
             value="<?php echo @$nompst[$modif]['titre'];?>"/><br />

          Catégorie : <input type="number" name="categorie"
              value="<?php echo @$nompst[$modif]['categorie'];?>"/><br /><br />
          
        Contenu :<br /><textarea rows="8" cols="60" name="contenu"><?php echo @$nompst[$modif]['contenu'];?>
                       </textarea><br /><br />


        <?php
            if (  isset($_GET['modifier']) ) 
            { 
              echo '<input type="submit" value="Modifier" />';
            }
            else
            { 
              echo '<input type="submit" value="Ajouter" />';
            }
        ?>

        </p>
    </form>
    
    <table>
      <tr class="ad_tr_liste">
        <td class="ad_td_auteur">Auteur</td>
        <td class="ad_td_titre">Titre</td>
        <td class="ad_td_cetegorie">Catég.</td>
        <td class="ad_td_date_ajout">Date d'ajout</td>
        <td class="ad_td_date_modif">Dernière modification</td>
        <td class="ad_td_action">Action</td>
      </tr>



      <?php

        echo '<p style="text-align: center">' . count($nompst) . ' nouvelles actuellement en ligne';
        echo '<p style="text-align: center">' . ' Liste des nouvelles:';

        for ($i=0; $i<count($nompst); $i++)
        {
          echo '<tr>';
          echo '<td class="ad_td_auteur">'      . $nompst[$i]['auteur']     . '</td>'; 
          echo '<td class="ad_td_titre">'       . $nompst[$i]['titre']      . '</td>';
          echo '<td class="ad_td_cetegorie">'   . $nompst[$i]['categorie']  . '</td>';
          echo '<td class="ad_td_date_ajout">'  . substr($nompst[$i]['dateAjout'],0,10)  . '</td>';
          echo '<td class="ad_td_date_modif">'  . substr($nompst[$i]['dateModif'],0,10)  . '</td>';
          echo '<td class="ad_td_action">'      .
               '<a href="?modifier=', $nompst[$i]['id'], '">Modifier</a><br>
                <a href="?supprimer=', $nompst[$i]['id'], '">Supprimer</a>' .
               '</td>';
          echo '</tr>';
        }
      ?>

    </table>


  </body>
</html>

<!-- <a href="?supprimer=', $news->id(), '">Supprimer</a> -->


        
