<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
  <head>
    <title>Administration</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="blog.css">
    <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
  </head>
  
  <body>
    <p><a href=".">Accéder à l'accueil du site</a></p>

      <div class="formulaire_commentaire">

        <form action="commentaire.php?id=<?php echo $id_news ?>" method="post">
            
          <span class="ad_lib_1">Nom :  </span><input type="text" name="nom"/><br />

          <span class="ad_lib_1">Prénom : </span><input type="text" name="prenom"/><br /><br />

          Commentaire :<br /><textarea rows="8" cols="60" name="commentaire"></textarea><br /><br /> 

          <input type="submit" value="Ajouter" />

       </form>
      </div>
        

  </body>
</html>