
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr">
  <head>
    <title>TP Blog vassigh</title>
    <link rel="stylesheet" href="blog.css">
    <meta charset="utf-8">
    <meta http-equiv="Content-type" content="text/html; charset=iso-8859-1" />
    
  </head>
  
  <body>
        
      <?php

          echo '<h1 style="text-align: center">' . $nompst['titre'] . '</h1>';
          echo '<h2 style="text-align: center">' . $nompst['auteur'] . '</h2>';

          echo '<p class="titre">' .
                 'Catégorie : '          . 
                  '<span class="texte">'  . $nompst['categorie']  . '</span>' .
                '</p>';

          echo '<p class="titre">' .
                 'Date de création : '          . 
                  '<span class="texte">'  . $nompst['dateAjout']  . '</span>' .
                '</p>';

          echo '<p class="titre">' .
                 'Date dernière modification : '          . 
                  '<span class="texte">'  . $nompst['dateModif']  . '</span>' .
                '</p>';

          echo '<p class="contenu">' . $nompst['contenu']  . '</p>';

      ?>
 
  </body>
</html>

